version: "3.9"
services:
  postgres:
    image: postgres:15.3-alpine
    ports:
      - 5496:5432
    environment:
      - POSTGRES_USER=akki
      - POSTGRES_PASSWORD=selection
      - POSTGRES_DB=selection
  
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://akki:selection@192.168.23.128:5496/selection?sslmode=disable
    depends_on:
      - postgres
    command: ["/app/main"]